ALTER TABLE characters ALTER COLUMN name DROP DEFAULT;
ALTER TABLE characters ALTER COLUMN race DROP DEFAULT;
ALTER TABLE characters ALTER COLUMN characterClass DROP DEFAULT;
ALTER TABLE characters ALTER COLUMN level DROP DEFAULT;
